version: "3.4"

services:
    feepercentage:
        image: feepercentage
        build:
            context: .
            dockerfile: FeePercentage/Dockerfile
        ports:
            - 7000:5000
            - 7001:5001
        env_file:
            - .env

    feepercentage-test:
        build:
            context: .
            dockerfile: FeePercentage.Tests/Dockerfile

    calculatefee:
        image: calculatefee
        build:
            context: .
            dockerfile: CalculateFee/Dockerfile
        ports:
            - 5000:5000
            - 5001:5001
        env_file:
            - .env
        depends_on:
            - feepercentage

    calculatefee-test:
        build:
            context: .
            dockerfile: CalculateFee.Tests/Dockerfile
        env_file: 
            - .env.tests
