version: "3.4"

services:
    taxajuros:
        image: taxajuros
        build:
            context: .
            dockerfile: TaxaJuros/Dockerfile
        ports:
            - 6000:5000
            - 6001:5001
        env_file:
            - .env

    calulajuros:
        image: calulajuros
        build:
            context: .
            dockerfile: CalulaJuros/Dockerfile
        ports:
            - 5000:5000
            - 5001:5001
        env_file:
            - .env
        depends_on:
            - taxajuros
