version: "3.4"

services:
    feepercentage:
        image: feepercentage
        build:
            context: .
            dockerfile: FeePercentage/Dockerfile
        ports:
            - 6000:5000
        env_file:
            - .env

    calculatefee:
        image: calculatefee
        build:
            context: .
            dockerfile: CalculateFee/Dockerfile
        ports:
            - 5000:5000
        env_file:
            - .env
        depends_on:
            - feepercentage
